version: "3.8"
   
services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./pgdata/db:/var/lib/postgresql/data/
    server:
        container_name: server
        build:
          context: ./server
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - db
        
volumes:
    pgdata:
    node_modules:
