version: "3.8"
   
services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./pgdata/db:/var/lib/postgresql/data/
    server:
        container_name: server
        build:
          context: ./server
        command: gunicorn core.wsgi --bind 0.0.0.0:8000 --reload
        volumes:
            - ./server:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - db
    nginx:
      image: nginx:latest
      restart: always
      ports:
        - 1200:8080
      volumes:
        - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
        - ./server/static:/static
      depends_on:
        - client

        
volumes:
    pgdata:
    node_modules:
