# Generated by Django 4.1.4 on 2022-12-24 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0009_remove_userbook_finished_at_remove_userbook_progress_and_more'),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='for_book',
        ),
        migrations.AddField(
            model_name='review',
            name='userbook',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='userbooks.userbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
