POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "username": "rashed",
  "password": "qwerty1200"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### logout
POST http://localhost:8000/api/auth/logout/
Content-Type: application/json
Authorization: Token {{auth_token}}

### me
GET http://localhost:8000/api/auth/me
Content-Type: application/json
Authorization: Token {{auth_token}}

### Create Book
POST http://localhost:8000/api/books/
Content-Type: application/json
Authorization: Token {{auth_token}}

{
  "title": "book 10",
  "authors": "knight",
  "language": "en",
  "pages": 1200
}


### Search For a book
GET http://localhost:8000/api/books/search?title=book&authors=knight&limit=5&offset=0
Content-Type: application/json


### Get Book
GET http://localhost:8000/api/books/1
Content-Type: application/json
Authorization: Token {{auth_token}}

### Create Genere
POST http://localhost:8000/api/books/genres/
Content-Type: application/json
Authorization: Token {{auth_token}}

{
  "name": "History"
}

### Get Generes
GET http://localhost:8000/api/books/genres/
Content-Type: application/json

