# Generated by Django 4.1.4 on 2022-12-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0002_alter_userbook_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='shelf',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_userbooks', to='userbooks.shelf'),
        ),
    ]
