# Generated by Django 4.1.4 on 2022-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0003_alter_userbook_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='shelf',
        ),
        migrations.AddField(
            model_name='userbook',
            name='shelf',
            field=models.ManyToManyField(blank=True, to='userbooks.shelf'),
        ),
    ]
