# Generated by Django 4.1.4 on 2022-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0004_remove_userbook_shelf_userbook_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='shelf',
            field=models.ManyToManyField(blank=True, related_name='all_userbooks', to='userbooks.shelf'),
        ),
    ]
