# Generated by Django 4.1.4 on 2022-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0005_alter_userbook_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='shelf',
            new_name='shelves',
        ),
    ]
