# Generated by Django 4.1.4 on 2022-12-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('books', '0006_alter_genre_name'),
        ('userbooks', '0006_rename_shelf_userbook_shelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', unique=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_userbooks', to='reviews.review'),
        ),
    ]
