# Generated by Django 4.1.4 on 2022-12-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userbooks', '0008_alter_userbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='progress_updated_at',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='review',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='started_at',
        ),
        migrations.AddField(
            model_name='userbook',
            name='is_currently_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserBookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('progress_updated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('userbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_sessions', to='userbooks.userbook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
