# Generated by Django 4.1.4 on 2023-01-01 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbooks', '0009_remove_userbook_finished_at_remove_userbook_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooksession',
            name='progress',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
