# Generated by Django 4.1.4 on 2023-01-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_created_by_alter_genre_created_by'),
        ('userbooks', '0011_alter_shelf_created_by_alter_userbook_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_userbooks', to='books.book'),
        ),
    ]
